environment:
  MINGW: C:\Qt\Tools\mingw492_32
  CMAKE_BUILD_TYPE: Release
  # set to d if debug build

  matrix:
    # Visual Studio build
    - generator: "Visual Studio 12 Win64"
      compiler_type: "vs12-x64"
      cmake_args: ""

    # MingGW x86 build
    - generator: "MinGW Makefiles"
      CMAKE_PREFIX_PATH: C:\Qt\5.5\mingw492_32
      CMAKE_C_COMPILER: gcc
      CMAKE_CXX_COMPILER: g++ 
      CMAKE_MAKE_PROGRAM: mingw32-make.exe
      compiler_type: "mingw32"

    # included directx headers incompatible with mingw
      cmake_args: ""

shallow_clone: true

init:
  # cmake errors if sh on the path
  - rm "C:\Program Files\Git\usr\bin\sh.exe"
  - set Path=%MINGW%\bin;%Path%

before_build:
  # generate project files or makefiles
  - cd C:\projects\yabause\yabause
  - mkdir build
  - cd build
  - cmake -G "%generator%" %cmake_args% ..

build_script:
  - if ["%compiler_type%"]==["mingw32"] cmake --build .

  # force a release build and only show errors to shorten output
  - if ["%compiler_type%"]==["vs12-x64"] msbuild vcdextract.sln /p:configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
